import type { Abi } from "viem";
import AGT from "@/abis/AGT.json";
import JokesContest from "@/abis/JokesContest.json";

// The ABI JSON generated by Foundry is valid, but TypeScript can't infer literal "function" etc.
// Cast to viem's Abi type for wagmi.
export const agtAbi = AGT as unknown as Abi;
export const jokesContestAbi = JokesContest as unknown as Abi;
